# Generated by Django 3.1.1 on 2020-09-10 06:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('collected_price', models.PositiveIntegerField()),
                ('base_price', models.PositiveIntegerField()),
                ('shipping_price', models.PositiveIntegerField(blank=True)),
                ('is_shipped', models.BooleanField(default=True)),
                ('date', models.DateField(default=datetime.date(2020, 9, 10))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
