# Generated by Django 3.1.1 on 2020-09-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20200910_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_shipped',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_price',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_mode',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
